name: Cypress Tests
on: push
  push:
    paths: 
    - 'cypress/e2e/5-tugas-and-quiz/2-demowebshop/*.cy.js'

jobs:
  cypress-run:
    name: Cypress run 
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress Test WebShop
        uses: cypress-io/github-action@v6
        with:
          spec: |
            cypress/e2e/5-tugas-and-quiz/2-demowebshop/register.cy.js
            cypress/e2e/5-tugas-and-quiz/2-demowebshop/login.cy.js
          browser: chrome
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos